version: '3.8'
services:
  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./services/nginx:/usr/share/nginx/html
    restart: always

  alpine-http:
    build:
      context: ./services/alpine-http
      dockerfile: Dockerfile
    ports:
      - "8081:8000"
    restart: always

  chromadb:
    build:
      context: ./services/chromadb
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - chromadb-data:/chromadb/data
    restart: always
volumes:
  chromadb-data:
