version: '3.8'
services:
  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./services/nginx:/usr/share/nginx/html
    restart: always

  alpine-http:
    build:
      context: ./services/alpine-http
      dockerfile: Dockerfile
    ports:
      - "8081:8000"
    restart: always
