version: '3.8'
services:
  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile
    ports:
      - "8082:80"
    volumes:
      - ./services/nginx:/usr/share/nginx/html
    restart: always

  alpine-http:
    build:
      context: ./services/alpine-http
      dockerfile: Dockerfile
    ports:
      - "8081:8000"
    restart: always

  open-webui-ollama:
      build:
        context: ./services/open-webui-ollama
        dockerfile: Dockerfile
      ports:
        - "8080:8080"
      restart: always
      volumes:
      - ollama:/root/.ollama # Map the 'ollama' volume to /root/.ollama in the container
      - open-webui:/app/backend/data # Map the 'open-webui' volume to /app/backend/data in the container

  qdrant:
    build:
      context: ./services/qdrant
      dockerfile: Dockerfile
    container_name: qdrant
    networks:
      - demo
    restart: unless-stopped
    ports:
      - "6333:6333"

networks:
  demo:
    driver: bridge

volumes:
  ollama: # Define the 'ollama' named volume
  open-webui: # Define the 'open-webui' named volume
  
