version: '3.8'
services:
  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile
    ports:
      - "8082:80"
    volumes:
      - ./services/nginx:/usr/share/nginx/html
    restart: always

  alpine-http:
    build:
      context: ./services/alpine-http
      dockerfile: Dockerfile
    ports:
      - "8081:8000"
    restart: always

  open-webui:
    build:
      context: ./services/open-webui
    container_name: open-webui
    ports:
      - "3000:8080"
    volumes:
      - open-webui:/app/backend/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always      

  ollama:
    build:
      context: ./services/ollama
      dockerfile: Dockerfile
    ports:
      - "11434:11434"
    volumes:
    - ollama:/root/.ollama # Map the 'ollama' volume to /root/.ollama in the container
    restart: always # Automatically restart the container on failure
    

  qdrant:
    build:
      context: ./services/qdrant
      dockerfile: Dockerfile
    container_name: qdrant
    networks:
      - demo
    restart: unless-stopped
    ports:
      - "6333:6333"

networks:
  demo:
    driver: bridge

volumes:
  open-webui: # Define the 'open-webui' named volume
  
