version: '3.8'
services:
  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile
    ports:
      - "8082:80"
    volumes:
      - ./services/nginx:/usr/share/nginx/html
    restart: always

  alpine-http:
    build:
      context: ./services/alpine-http
      dockerfile: Dockerfile
    ports:
      - "8081:8000"
    restart: always

  open-webui-ollama:
      build:
        context: ./services/open-webui-ollama
        dockerfile: Dockerfile
      ports:
        - "8080:8080"
      restart: always

  qdrant:
    build:
      context: ./services/qdrant
      dockerfile: Dockerfile
    container_name: qdrant
    networks:
      - demo
    restart: unless-stopped
    ports:
      - "6333:6333"

networks:
  demo:
    driver: bridge
  
