version: '3.8'
services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    volumes:
      - ../openWebUILocalVolume:/app/backend/data
    depends_on:
      - ollama
    ports:
      - 8080:8080
    environment: # https://docs.openwebui.com/getting-started/env-configuration#default_models
      - OLLAMA_BASE_URLS=http://host.docker.internal:7869 #comma separated ollama hosts
      - ENV=dev
      - WEBUI_AUTH=False
      - WEBUI_NAME=baby
      - WEBUI_URL=http://localhost:8080
      - WEBUI_SECRET_KEY=123456
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    networks:
      - ollama-docker   

  ollama:
    image: ollama/ollama:latest
    ports:
      - 7869:11434
    volumes:
      - ../ollamaLocalVolume:/root/.ollama # Map '../ollamaLocalVolume' to /root/.ollama in the container
    restart: unless-stopped

  qdrant:
    build:
      context: ./services/qdrant
      dockerfile: Dockerfile
    container_name: qdrant
    networks:
      - demo
    restart: unless-stopped
    ports:
      - "6333:6333"

networks:
  ollama-docker:
    external: false

