FROM qdrant/qdrant

# Optional: You can add customizations here if necessary, such as copying configuration files, etc.
# COPY ./config/qdrant-config.toml /qdrant/config/

# Expose the same port
EXPOSE 6333

# Default command (in this case, it's just the default entrypoint)
#CMD ["qdrant"]
