# Use the specified base image
FROM ollama/ollama

# Ensure directories exist (optional)
RUN mkdir -p /root/.ollama

# Expose the application port
EXPOSE 11434

# Set the default command if needed (usually already defined in the base image)
#CMD ["ollama" "pull" "nomic-embed-text"]